### ISSUE TITLE
[QUESTION] Please add some detail and docs

### ISSUE THREAD

**Issue by mnlbox** [padosoft/kill-process#5]
Hi @lopadova ,
Can you explain `dry` option more? I can't understand that.
Also I think a little more detail and docs can be useful.

Thanks for your attention and for this awesome bash. 😉

**Comment by lopadova** [comment]
hi @mnlbox 
the dry mode is for testing.
if you run the script in dry mode (instead of kill mode), the script runs identically with kill mode, but if the script catch a process to kill:
- in kill mode, the script exec kill command to kill these process
- in dry mode, the script DO NOT exec the kill command.

See for example:
line 218 the IF statement:
https://github.com/padosoft/kill-process/blob/master/killprocess.sh#L218

best regards.
